
import type{ ChannelCardProps } from "../types";

export const channelData: ChannelCardProps[] = [
  {
    id: 1,
    title: "Team Email",
    image: "/images/email.svg",
    alt: "Email",
    width: 42,
    height: 42,
    aosDelay: 150,
  },
  {
    id: 2,
    title: "WhatsApp",
    image: "/images/whatsapp.svg",
    alt: "WhatsApp",
    width: 42,
    height: 42,
    aosDelay: 200,
  },
  {
    id: 3,
    title: "Facebook Messenger",
    image: "/images/messanger.svg",
    alt: "Facebook Messenger",
    width: 42,
    height: 42,
    aosDelay: 250,
  },
  {
    id: 4,
    title: "Instagram Messenger",
    image: "/images/instagram.svg",
    alt: "Instagram",
    width: 42,
    height: 42,
    aosDelay: 300,
  },
  {
    id: 5,
    title: "Calling",
    image: "/images/calling.svg",
    alt: "Calling",
    width: 42,
    height: 42,
    aosDelay: 350,
  },
  {
    id: 6,
    title: "Forms",
    image: "/images/form.svg",
    alt: "Forms",
    width: 42,
    height: 42,
    aosDelay: 400,
  },
  {
    id: 7,
    title: "Website Live Chat",
    image: "/images/message.svg",
    alt: "Website Live Chat",
    width: 42,
    height: 42,
    aosDelay: 450,
  },
  {
    id: 8,
    title: "SMS",
    image: "/images/sms.svg",
    alt: "SMS",
    width: 42,
    height: 42,
    aosDelay: 500,
  },
];