import {
  ResponseTimeIcon,
  TeamCollaborationIcon,
  CentralizedCommunicationIcon,
  CustomerSupportIcon,
  WorkflowIcon,
} from "../components/Icons/ModernBusiness";
import type { ChooseDataType } from "../types";

export const chooseData: ChooseDataType[] = [
  {
    id: 1,
    eventKey: "faster-response",
    title: "Faster Response Times",
    description: "Manage conversations from every channel in one inbox and respond faster without switching tools.",
    delay: 100,
    Icon: ResponseTimeIcon,
    image: "/images/better-teeam-collabration-lg.jpg",
    imageAlt: "Better team collaboration",
    infoImage: "/images/team-collabration-msg-lg.png",
    infoImageAlt: "Team collaboration message",
  },
  {
    id: 2,
    eventKey: "team-collaboration",
    title: "Better Team Collaboration",
    description: "Keep support, sales, and operations teams aligned with shared communication visibility.",
    delay: 200,
    Icon: TeamCollaborationIcon,
    image: "/images/better-team-collaboration-lg.jpg",
    imageAlt: "Better Team Collaboration",
    infoImage: "/images/team-collabration-msg-lg.png",
    infoImageAlt: "Team collaboration message",
  },
  {
    id: 3,
    eventKey: "centralized-communication",
    title: "Centralized Communication",
    description: "Manage all customer conversations from one unified platform with complete history tracking.",
    delay: 300,
    Icon: CentralizedCommunicationIcon,
    image: "/images/centralized-communication-lg.jpg",
    imageAlt: "Centralized communication",
    infoImage: "/images/team-collabration-msg-lg.png",
    infoImageAlt: "Team collaboration message",
  },
  {
    id: 4,
    eventKey: "customer-experience",
    title: "Improved Customer Experience",
    description: "Deliver faster, consistent, and personalized support across every communication channel.",
    delay: 400,
    Icon: CustomerSupportIcon,
    image: "/images/improved-customer-experience-lg.jpg",
    imageAlt: "Customer experience",
    infoImage: "/images/team-collabration-msg-lg.png",
    infoImageAlt: "Team collaboration message",
  },
  {
    id: 5,
    eventKey: "workflow-management",
    title: "Smarter Workflow Management",
    description: "Organize conversations, automate processes, and improve team productivity with centralized workflows.",
    delay: 500,
    Icon: WorkflowIcon,
    image: "/images/smarter-workflow-management-lg.jpg",
    imageAlt: "Workflow management",
    infoImage: "/images/team-collabration-msg-lg.png",
    infoImageAlt: "Team collaboration message",
  },

];