export const ecosystemData = [
  {
    id: 1,
    title: "CRM",
    image: "/images/crm.png",
    alt: "crm-icon",
    width: 41,
    height: 42,
    cardClass: "crm-card",
    aosDelay: 400,
    aosDuration: 300,
    description:
      "Manage customer relationships, sales pipelines, leads, and follow-ups from one centralized platform. Help your sales team close deals faster and build stronger customer relationships.",
    features: [
      "Lead & Contact Management",
      "Sales Pipeline Tracking",
      "Automated Follow-Ups",
      "Customer Activity Timeline",
    ],
  },
  {
    id: 2,
    title: "Invoicing",
    image: "/images/invoicing.png",
    alt: "invoicing",
    width: 35,
    height: 40,
    cardClass: "invoice-card",
    aosDelay: 500,
    aosDuration: 300,
    description:
      "Create, send, and manage invoices effortlessly while tracking payments in real time. Simplify your billing operations and improve cash flow management.",
    features: [
      "Instant Invoice Creation",
      "Online Payment Tracking",
      "Automated Billing Workflows",
      "Payment Reminders",
    ],
  },
  {
    id: 3,
    title: "Asset Management",
    image: "/images/asset-managment.png",
    alt: "asset-management",
    width: 53,
    height: 40,
    cardClass: "ast-card",
    aosDelay: 600,
    aosDuration: 300,
    description:
      "Track, monitor, and manage company assets throughout their lifecycle. Maintain complete visibility across equipment, devices, and business resources.",
    features: [
      "Asset Tracking & Monitoring",
      "Maintenance Management",
      "Lifecycle Tracking",
      "Asset Performance Insights",
    ],
  },
  {
    id: 4,
    title: "Stock",
    image: "/images/stock.png",
    alt: "stock",
    width: 36,
    height: 40,
    cardClass: "stock-card",
    aosDelay: 700,
    aosDuration: 300,
    description:
      "Monitor inventory levels, stock movement, and warehouse operations from one platform. Prevent stock shortages and improve inventory accuracy.",
    features: [
      "Real-Time Inventory Tracking",
      "Low Stock Alerts",
      "Multi-Location Inventory",
      "Stock Movement History",
    ],
  },
  {
    id: 5,
    title: "Order Management",
    image: "/images/order.png",
    alt: "order",
    width: 40,
    height: 40,
    cardClass: "ord-card",
    aosDelay: 800,
    aosDuration: 300,
    description:
      "Streamline order processing, fulfillment, and delivery workflows. Manage customer orders efficiently from purchase to delivery.",
    features: [
      "Order Workflow Management",
      "Delivery Tracking",
      "Fulfillment Automation",
      "Customer Order History",
    ],
  },
  {
    id: 6,
    title: "Analytics",
    image: "/images/analytics-icon.png",
    alt: "analytics-icon",
    width: 41,
    height: 40,
    cardClass: "analyt-card",
    aosDelay: 900,
    aosDuration: 300,
    description:
      "Turn business data into meaningful insights with powerful analytics and real-time performance reporting.",
    features: [
      "Business Performance Reports",
      "Customer Insights",
      "Revenue Analytics",
      "Custom Dashboards",
    ],
  },
];